import type { Category, RequestDetails } from "../src/types";
export function rng(seed: number): () => number { let state = seed >>> 0; return () => { state ^= state << 13; state ^= state >>> 17; state ^= state << 5; return (state >>> 0) / 4294967296; }; }
const definitions: Record<Category, { hosts: string[]; paths: string[]; types: RequestDetails["resourceType"][]; thirdParty: boolean[] }> = {
  content: { hosts: ["cdn.example.test", "static.example.test", "api.example.test", "images.example.test"], paths: ["/assets/app.js", "/images/hero.webp", "/api/articles", "/fonts/site.woff2", "/styles/main.css", "/media/video.mp4"], types: ["script", "image", "xmlhttprequest", "font", "stylesheet", "media"], thirdParty: [false, false, false, true] },
  ad: { hosts: ["ads.vendor.test", "adserver.example.test", "sponsor.cdn.test", "campaign.media.test"], paths: ["/ads/banner.js", "/serve/advert.gif", "/sponsored/slot", "/campaign/impression", "/promo/creative.webp", "/click/redirect"], types: ["script", "image", "sub_frame", "xmlhttprequest"], thirdParty: [true, true, true, false] },
  tracker: { hosts: ["analytics.vendor.test", "metrics.example.test", "telemetry.service.test", "pixel.collector.test"], paths: ["/collect/event", "/tracking/pixel.gif", "/analytics/pageview", "/beacon", "/metrics/session", "/telemetry/batch"], types: ["script", "image", "xmlhttprequest"], thirdParty: [true, true, false] },
};
const pick = <T>(random: () => number, values: readonly T[]): T => values[Math.floor(random() * values.length)];
export interface Example { request: RequestDetails; category: Category }
export function generate(count: number, seed: number): Example[] { const random = rng(seed), categories: Category[] = ["content", "ad", "tracker"], output: Example[] = []; for (let i = 0; i < count; i++) { const category = categories[i % 3], d = definitions[category], host = pick(random, d.hosts), path = pick(random, d.paths); output.push({ category, request: { url: `https://${host}${path}?v=${Math.floor(random() * 1000)}`, sourceUrl: "https://publisher.example.test/article", resourceType: pick(random, d.types), thirdParty: pick(random, d.thirdParty) } }); } return output; }
